baseURL = "https://oxddr.github.io/kingsofwarpl"
copyright = "2021 Jan Åukaszewicz. Kings of War Polska is an unofficial site not affiliated with Mantic Games. Kings of War is a trademark of Mantic Games."
languageCode = "pl"
theme = ["hugo-initio"]
title = "Strona polskiej spoÅ‚ecznoÅ›ci Kings of War"
[[menu.main]]
identifier = "liga"
name = "Liga"
weight = 9
[[menu.main]]
name = "Ranking 2021"
parent = "liga"
url = "ranking"
weight = 6
[[menu.main]]
name = "Regulamin 2021"
parent = "liga"
url = "bylaw"
weight = 4
[[menu.main]]
name = "O lidze"
parent = "liga"
url = "league"
weight = 2
[[menu.main]]
name = "Wydarzenia"
url = "events"
weight = 8
[[menu.main]]
name = "Jak zaczÄ…Ä‡?"
url = "getting_started"
weight = 5
[[menu.main]]
name = "O grze"
url = "about"
weight = 3
[[menu.main]]
name = "ğŸ "
weight = 1
[params]
DateForm = "January 2, 2006"
avatar = "/images/logo2.png"
avatarclass = "square22"
banner = "/images/kowbattle.jpeg"
description = "Strona polskiej spoÅ‚ecznoÅ›ci gry Kings of War"
featured_image = "/images/kowbattle.jpeg"
site_logo = "/images/logo.png"
