baseURL = 'https://kingsofwar.pl'
languageCode = 'pl'
title = 'Strona polskiej spoÅ‚ecznoÅ›ci Kings of War'
copyright = "2021 Jan Åukaszewicz. Kings of War Polska is an unofficial site not affiliated with Mantic Games. Kings of War is a trademark of Mantic Games."

theme = ["hugo-initio"]

[params]
  banner = "/images/kowbattle.jpeg"
  site_logo = "/images/logo.png"
  avatar = "/images/logo2.png"
  avatarclass = "square22"
  description = 'Strona polskiej spoÅ‚ecznoÅ›ci gry Kings of War'
  DateForm = "2006-01-02"

[menu]
  [[menu.main]]
    name = 'ğŸ '
    weight = -110
  [[menu.main]]
    name = "O grze"
    url = "about"
    weight = 5
  [[menu.main]]
    name = 'Jak zaczÄ…Ä‡?'
    weight = 10
    url = "getting_started"
  [[menu.main]]
    name = "Jak nas znaleÅºÄ‡?"
    weight = 20
    url = "community"
  [[menu.main]]
    name = "Wydarzenia"
    url = "events"
    weight = 30
  [[menu.main]]
    identifier = "liga"
    name = "Liga"
    weight = 40
  [[menu.main]]
    name = "O lidze"
    url = "league"
    weight = 5
    parent = "liga"
  [[menu.main]]
    name = "Regulamin 2021"
    url = "bylaw"
    parent = "liga"
    weight = 10
  [[menu.main]]
    name = "Ranking 2021"
    url = "ranking"
    parent = "liga"
    weight = 20
